name: Build and Push QSIQC Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Build QSIQC docker image
        run: sh ./docker_ci_scripts/docker-build.sh \
          "${{github.sha}}" "richford"

      - name: Build a tagged image
        if: startsWith(github.event.ref, 'refs/tags')
        run: |
          sh ./docker_ci_scripts/docker-build.sh \
            "${GITHUB_REF:10}" "richford"

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push QSIQC docker image
        if: github.ref == 'refs/heads/master' || startsWith(github.event.ref, 'refs/tags')
        run: sh ./docker_ci_scripts/docker-push.sh "richford"
